version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: visual-genius-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password}
      POSTGRES_DB: ${POSTGRES_DB:-your_db_name}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-your_db_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - visual-genius-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visual-genius-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database - uses POSTGRES_URL format (falls back to placeholders)
      POSTGRES_URL: ${POSTGRES_URL:-"postgresql://${POSTGRES_USER:-your_db_user}:${POSTGRES_PASSWORD:-your_secure_password}@postgres:5432/${POSTGRES_DB:-your_db_name}"}
      
      # Azure OpenAI
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${AZURE_OPENAI_DEPLOYMENT_NAME}
      
      # Unsplash API
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      
      # Application
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3001:3000"
    networks:
      - visual-genius-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  visual-genius-network:
    driver: bridge
